name: places_search
description: Custom Google places autocomplete widget for Android and iOS
version: 1.0.0
homepage: https://github.com/jslattery26Packages/Google-AutoComplete-TextField-Flutter

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  rxdart: ^0.27.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  collection: ^1.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.0
  flutter_lints: ^2.0.3

flutter:
  assets:
    - images/location.json
