name: places_search
description: Custom Google places autocomplete widget for Android and iOS
version: 1.0.0
homepage: https://github.com/jslattery26Packages/Google-AutoComplete-TextField-Flutter

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.3
  rxdart: ^0.27.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  freezed: ^2.4.3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.3

dependency_overrides:
  collection: ^1.18.0

flutter:
  assets:
    - images/location.json
