name: places_search
description: Custom Google places autocomplete widget for Android and iOS
version: 1.0.0
homepage: https://github.com/jslattery26Packages/Google-AutoComplete-TextField-Flutter
publish_to: none
environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  rxdart: ^0.28.0
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.3.1
  json_annotation: ^4.8.1
  hooks_riverpod: ^2.4.10
  flutter_hooks: ^0.20.5
  flutter_use: ^0.0.4
  flutter_google_places_sdk: ^0.3.9

dev_dependencies:
  custom_lint: ^0.6.8
  freezed: ^2.4.6
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_lints: ^5.0.0
  test: ^1.25.2
  riverpod_generator: ^2.3.7
  riverpod_lint: ^2.3.5

dependency_overrides:
  collection: ^1.18.0
